### ISSUE TITLE
Steam Path not found, possible solution

### ISSUE THREAD

**Issue by notKamui** [optix2000/totsugeki#1]
First things first: This is an insanely good job and kind of a life saver, so thank you very much !

I have a possible simple amelioration, which would be prompting the user for Steam's exe's path if it's not found at the usual place (some people don't put it in C:). This would require a simple config file to be placed in the same folder as totsugeki's exe.

**Comment by notKamui** [comment]
Of course, a txt file should be enough. Though, there might be future improvements and modularity, in which case a yaml or json file would be more appropriate.

**Comment by fefo-dev** [comment]
Adding to that please add a way to completely disable Steam launching for those who use external launchers (eg. Playnite).

**Comment by hollusion** [comment]
This might work for you: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-hardlink

**Comment by notKamui** [comment]
> This might work for you: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-hardlink

of course, but this is only a temporary solution and not very practical, nor user friendly, nor "clean". At this point, changing the path in the code and compiling the exe is just better.

**Comment by optix2000** [comment]
Having configurable options is planned. Will make sure configuring Steam path and disabling launch is included.

**Comment by optix2000** [comment]
@fefo-dev As a workaround for now, you can launch the game first and _then_ launch totsugeki. totsugeki won't try to launch the game if it's already running.

**Comment by ToadKing** [comment]
You should be able to autodetect Steam for 99% of installs. The Steam install path should just be in the registry (key `HKCU\Software\Valve\Steam`, value `SteamExe`)

**Comment by optix2000** [comment]
#3 is a way better solution, but I'll keep this open to track the config option for disabling autolaunch.

**Comment by optix2000** [comment]
You can now create a shortcut and add `-no-launch` to stop it from launching GGST.


![image](https://user-images.githubusercontent.com/1121068/127271607-8866b52b-ce69-4661-9fa2-50f00833a1aa.png)
