### ISSUE TITLE
Request: support/guide to using with Proton for Linux gamers

### ISSUE THREAD

**Issue by itsspher** [optix2000/totsugeki#10]
I'd really like a guide or an AppImage or a native linux binary for this program, for use by Linux gamers.

**Comment by notKamui** [comment]
this would be an entirely different work since there are a lot of Windows API calls here, but is definitely something to consider i feel. (especially with SteamDeck coming soon)

**Comment by optix2000** [comment]
Unfortunately to make this native for Linux, it would need a rewrite as memory patching is fundamentally different between Windows and Linux. 

I don't have a Linux gaming machine to develop on, so this is unlikely to happen.

If you're running GGST through Wine, and it doesn't work, you can report any issues and I'll try do some best-effort fixes against Wine.

**Comment by optix2000** [comment]
For Proton/Wine, you can try launching `totsugeki.exe` with Wine and it should theoretically work.

```sh
 "/path/to/SteamLibraryLinux/steamapps/common/Proton 3.7/dist/bin/wine64" "/path/to/totsugeki.exe"
```

**Comment by FrozenFish24** [comment]
I was able to get totsugeki working properly with proton by slightly modifying [this script](https://gist.github.com/smo0z/620d9d98e27dbba01345a5b21948f545) to get it to run under the same prefix as Strive.

Here's [my changes](https://gist.github.com/FrozenFish24/32373f530dfdb1b2cbb54309a4fa9aaa), (Assumes totsugeki is in the game directory and you want to use Proton - Experimental)

**Comment by optix2000** [comment]
I would consider adding `-no-launch` to Totsugeki so it doesn't try to launch Strive outside of Proton.

**Comment by FrozenFish24** [comment]
:+1: added it to the gist

**Comment by optix2000** [comment]
Since it looks like Totsugeki works with wine/Proton, I'll close this out.
