### ISSUE TITLE
no-proxy option closes prematurely

### ISSUE THREAD

**Issue by Nimamoh** [optix2000/totsugeki#11]
I expected `-no-proxy` to launch ggst patching it to request on 127.0.0.1:21611 but it appears it only launch ggst vanilla

![image](https://user-images.githubusercontent.com/16213090/127496776-1399b61a-c12e-432c-87ca-3aff572bf3f3.png)

**Comment by optix2000** [comment]
Ah, this is a race condition that I didn't catch when I was testing it. Thanks for the report. Will look into fixing this.
