### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by optix2000** [optix2000/totsugeki#13]
Add option to cache certain API's (ie stats) with some level of consistency guarantee (ie expire cache on write to simulate write through cache).

Requires API's are identical between calls, which needs additional research.

Could add batching functionality if certain calls are always made together.

Mark as unsafe advanced feature only, as this removes the transparency guarantee.

**Comment by misterperson** [comment]
I could see it also being used for the News Feed which has has a heavy 1-3 second fetch time.

**Comment by badpunman** [comment]
Might as well hard code news feed to return static data. It seems quite useless a feature.

**Comment by Borengar** [comment]
API requests that get called a lot and could be cached:
- `/catalog/get_follow`. Invalidate on `/follow/follow_user` and `/follow/unfollow_user`.
- `/catalog/get_block`. Invalidate on `/follow/block_user` and `/follow/unblock_user`.

There's also `/lobby/get_vip_status`, but I have no idea what it does. Response is always empty for me.

**Comment by dons20** [comment]
`/lobby/get_vip_status` seems to be called anytime I'm qualifying for celestial challenge

**Comment by Borengar** [comment]
Thanks for the info. Might not be safe to cache it then. Can't really implement it either if I wanted to because I'm nowhere near celestial. 😆

**Comment by Borengar** [comment]
I created a PR for `/catalog/get_follow` and `/catalog/get_block` cache. #64

**Comment by optix2000** [comment]
Closing as @Borengar implemented all of them. 🙏
