### ISSUE TITLE
Looking at other people's R-Code

### ISSUE THREAD

**Issue by gaqsq** [optix2000/totsugeki#16]
Really small problem since most people don't use the inspect R-Code thing at all I guess, but currently when using the mod the load time is still the same when looking at other people's R-Code, that is, they're still really long.

I noticed that Totsugeki is still redirecting stuff when you look at someone's R-Code even though it's so long, so this might be something unavoidable since you're pulling someone else's information and not sending yours? I don't know how it works, but I'm opening the issue because this might have been something that was overlooked.

Pretty much everything I looked into loads way faster though, and I didn't encounter any other problems so far, thanks for the great mod.

**Comment by optix2000** [comment]
Looking at R-Codes should be fast**er** than normal, but not necessarily fast. My guess is it pulls all the players stats the same way it pulls your own stats during the title screen (ie it takes minutes).

I'll do some more digging to see how R-Codes are handled.

**Comment by optix2000** [comment]
Did some testing today. Looking at R-Codes will be about as slow as loading the main menu. A large portion of the requests at the title screen are just to load your own R-Code, one stat at a time. Likewise it looks like looking at other people's R-Codes makes the same requests so it's equally slow.

This is unfortunately not something that can be fixed easily without dissecting the protocol and coming up with a way for Totsugeki to batch stats requests. I'll be digging at the stats API (as it seems to be the slowest) in the next few weeks to see if there's any ways to make it faster.

Glad you find Totsugeki useful!

**Comment by gaqsq** [comment]
I see, thank you for looking into it, I thought this would be the case. It would be cool to be able to look at R-Codes faster to make following or blocking people actually useful, but it's not that big of a deal, we can only hope the developers fix the actual game now.
