### ISSUE TITLE
Not working - Network features disabled

### ISSUE THREAD

**Issue by nathanmrtns** [optix2000/totsugeki#18]
When I run totsugeki, it patches the process but when I press A, and start communicating, I don't see the posts on totsugeki window, and then the game gives me the message that the Network features are disabled because there is not internet connection. 

Is there a workaround for that?

**Comment by optix2000** [comment]
Can you paste or screenshot the logs so I can look into what happened?

Do you have a firewall running?

**Comment by nathanmrtns** [comment]
@optix2000 Disabling windows firewall did the trick
