### ISSUE TITLE
Carification in README

### ISSUE THREAD

**Issue by notKamui** [optix2000/totsugeki#2]
I've seen a lot of confusion on reddit about what the application actually does. Many people didn't understand the part about "patching Strive". Indeed it is ambiguous as to what it truly is. 

README should mention that it only touches the memory of the process (and not the actual game itself) specifically to forward the API call to the local server instead of Strive's server directly. 

(I'm not sure if this is what you intended to actually write from the start as the phrasing in this part seems like a simple typo / oversight)

**Comment by optix2000** [comment]
Didn't realize the Reddit post actually got read at all. Yeah I need to clean up the Readme a lot.

**Comment by optix2000** [comment]
Rewrote the readme all together. Should be more clear now.
