### ISSUE TITLE
Issue on Rank change on Online

### ISSUE THREAD

**Issue by SKNANK** [optix2000/totsugeki#20]
Issue on rank change on online lobby, after rank change, you get stuck on the same screen as it indefinitely loads

**Comment by Avre** [comment]
I have changed rank several times with no issue, doesn't seem to be a reproduceable problem?

**Comment by notKamui** [comment]
this didn't occur for me even though I changed floors several times yesterday on the latest version. 

i suspect it is a problem server side (as it is frequent even without totsugeki) in the same vein as the infinite load or "couldnt initiallize match".

**Comment by SKNANK** [comment]
ah ok cheers, probably just to do with the server then
