### ISSUE TITLE
game doesn't respond when floor changes

### ISSUE THREAD

**Issue by mateusPreste** [optix2000/totsugeki#21]
The game goes to a infinite load when ranking updates

**Comment by notKamui** [comment]
see issue [#20](https://github.com/optix2000/totsugeki/issues/20)

**Comment by optix2000** [comment]
Need a screenshot or a paste of the Totsugeki logs.

@notKamui is right, this looks the same as #20.

**Comment by maorgoldberg** [comment]
Hey I started experiencing this issue as well since starting to use this mod here is a paste of the logs:
```2021/08/02 18:13:54 "POST http://127.0.0.1:21611/api/statistics/set HTTP/1.1" from 127.0.0.1:61541 - 200 59B in 394.6622ms
2021/08/02 18:13:56 "POST http://127.0.0.1:21611/api/results/set HTTP/1.1" from 127.0.0.1:61541 - 200 59B in 1.3197429s
2021/08/02 18:13:56 "POST http://127.0.0.1:21611/api/replay/save HTTP/1.1" from 127.0.0.1:61541 - 200 68B in 440.7754ms
2021/08/02 18:16:03 "POST http://127.0.0.1:21611/api/statistics/set HTTP/1.1" from 127.0.0.1:61548 - 200 59B in 1.4352619s
2021/08/02 18:16:06 "POST http://127.0.0.1:21611/api/statistics/set HTTP/1.1" from 127.0.0.1:61548 - 200 59B in 343.0178ms
2021/08/02 18:16:08 "POST http://127.0.0.1:21611/api/results/set HTTP/1.1" from 127.0.0.1:61548 - 200 59B in 1.2849362s
2021/08/02 18:16:08 "POST http://127.0.0.1:21611/api/replay/save HTTP/1.1" from 127.0.0.1:61548 - 200 68B in 381.9175ms
2021/08/02 18:17:41 "POST http://127.0.0.1:21611/api/statistics/set HTTP/1.1" from 127.0.0.1:61552 - 200 59B in 1.4676051s
2021/08/02 18:17:45 "POST http://127.0.0.1:21611/api/statistics/set HTTP/1.1" from 127.0.0.1:61552 - 200 59B in 387.3419ms
2021/08/02 18:17:46 "POST http://127.0.0.1:21611/api/results/set HTTP/1.1" from 127.0.0.1:61552 - 200 59B in 1.30089s
2021/08/02 18:17:47 "POST http://127.0.0.1:21611/api/replay/save HTTP/1.1" from 127.0.0.1:61552 - 200 68B in 445.2386ms
2021/08/02 18:17:53 "POST http://127.0.0.1:21611/api/catalog/get_area HTTP/1.1" from 127.0.0.1:61552 - 200 202B in 343.2413ms
2021/08/02 18:17:54 "POST http://127.0.0.1:21611/api/catalog/get_floor HTTP/1.1" from 127.0.0.1:61552 - 200 224B in 348.791ms
2021/08/02 18:17:57 "POST http://127.0.0.1:21611/api/lobby/release_battle_area HTTP/1.1" from 127.0.0.1:61552 - 200 59B in 352.8766ms

**Comment by maorgoldberg** [comment]
Worth noting that I haven't experienced something like this in my 60 hours of play and its happened twice since I installed the mod yesterday (Don't have any other mods)

**Comment by optix2000** [comment]
To confirm, this happens when you rank up (or down), and you get moved to a new floor?

What sort of infinite load screen are you talking about? A connecting to server screen?

**Comment by optix2000** [comment]
Try the [latest release](https://github.com/optix2000/totsugeki/releases/latest) and let me know if it's still happening.

**Comment by optix2000** [comment]
Closing for now. Let me know if this is still happening.

**Comment by agustinmorantes** [comment]
Hi, I've been having this issue with the latest version, and it happened to me every time I changed floors (I installed totsugeki yesterday, and it's happened the 2 times I changed floors). The game just stays there waiting. I only have the screenshot right now, but will try to post totsugeki logs as soon as i can. 

![image](https://user-images.githubusercontent.com/21344464/131591367-3683787c-7c83-4355-85f6-40b8268726e8.png)

**Comment by optix2000** [comment]
Will need the logs for sure. Does it ever get unstuck if you wait a very long time?

**Comment by agustinmorantes** [comment]
Sorry for the wait. I had trouble recreating the issue consistently, it seems to happen randomly. I moved floors 3 times and only on the last one it stopped responding. I left it for about 30 minutes and it doesn't do anything, doesn't respond to input at all. Just stays there with te music and the animations. Here are the logs:
[totsugeki_log.txt](https://github.com/optix2000/totsugeki/files/7109388/totsugeki_log.txt)

**Comment by optix2000** [comment]
Hm, let me make a new build with some more debugging. I'm not seeing any failed requests in the log.

**Comment by Borengar** [comment]
I get that too sometimes now. Always gets stuck after `/lobby/release_battle_area`. It really seems to be random though. Yesterday it happened on the 3rd floor update. Today it was on the 1st.
Never played much without Totsugeki so I can't say anything about if this is normal GGST jank.
From the logs of agustinmorantes it looks like they only used the safe part of totsugeki, so not sure why it would get stuck.

**Comment by optix2000** [comment]
Yeah I'm gonna try adding some extra logging to log the beginning and end of each request and see if the connection is just stuck, or if it's just GGST jank outside of Totsugeki.

**Comment by optix2000** [comment]
Closing as it looks like this isn't happening anymore.
