### ISSUE TITLE
Totsugeki process is ended before GGST opens up

### ISSUE THREAD

**Issue by chrisvasqm** [optix2000/totsugeki#22]
Totsugeki process is ended before GGST opens up

I see the Totsugeki cmd prompt opens up when I double click the .EXE file, but right before GGST opens up, it closes and I don't see it in my Task Manager's Processes or Details tabs. 

I tried booting up the game, with and without Totsugeki, and I get around 2 minutes and 40 seconds of login time either way.

**Does this issue happen when you don't use Totsugeki?**
No.

**Totsugeki Version and logs**
Totsugeki v1.0.0 and GGST 1.07. Since the terminal is being closed I don't have access to any logs.

Version: 

**Steps to Reproduce**
1. Double click Totsugeki.exe
2. After GGST opens up, check if the Totsugeki cmd prompt is open or not

EDIT:

As mentioned by @oryxcallotis, opening Totsugeki.exe as an admin made it stay open and reduced my login time from 2 minutes and 40 seconds to about 48 seconds.

**Comment by chrisvasqm** [comment]
Thanks @oryxcallotis, it worked now as you said. I wonder why it behaves like that on some machines then...

**Comment by ToadKing** [comment]
If you try running it from a command line it might show an error message before it closes that could help debug this.

**Comment by notKamui** [comment]
Yeah, you don't need admin permissions ; what might be happening here is your firewall may not like it.

**Comment by optix2000** [comment]
> Happens with me, have to launch totsugeki as admin.

This should generally not be the case unless you're running Steam or GGST as admin.

I'll have to look into why the error messages don't pop up a window.

**Comment by chrisvasqm** [comment]
> > Happens with me, have to launch totsugeki as admin.
> 
> This should generally not be the case unless you're running Steam or GGST as admin.
> 
> I'll have to look into why the error messages don't pop up a window.

Yeah, I run it as an admin to be able to run some games that don't natively support controllers via the "Add non-steam games" feature.

I'll try to run it from cmd and adding it to the firewall.

**Comment by chrisvasqm** [comment]
I added the Firewall permissions to Totsugeki.exe, removed the "Run as admin" from the Compatibility window, and ran the file using the cmd but it got "access denied"

![image](https://user-images.githubusercontent.com/8799179/128443857-09f0b97a-8691-4346-a654-1fde9dee5eab.png)

Then I ran cmd as admin and it worked.

**Comment by optix2000** [comment]
> Yeah, I run Steam as an admin to be able to run some games that don't natively support controllers via the "Add non-steam games" feature.

This is expected. If you run Steam or GGST as admin you will need to run Totsugeki as admin, otherwise you will get access denied. Non-admin programs cannot access admin level programs, so in your case you'll either have to check "Run as Admin" in the compatability screen, or run it in an administrator command promt.

I'll leave this issue open to track why error messages don't pop up a window.

**Comment by optix2000** [comment]
Try out the new build here: https://github.com/optix2000/totsugeki/releases/tag/v1.1.1

Should properly throw an error when GGST is running as Administrator and Totsugeki is not.
