### ISSUE TITLE
Context Cancelled?

### ISSUE THREAD

**Issue by JackKellar** [optix2000/totsugeki#30]
![image](https://user-images.githubusercontent.com/88896098/129380681-0525042f-eeef-4afd-9822-c16d70793acb.png)

This happens at random. Yesterday it was fine even though it took about 4m to connect. I'm new to the game.

This check failed at the upload stage, and it kept failing for 2 hours today :( not sure if there's something I can do here.

The error it gave me was Failed to upload R-Code. I imagine this is on their end, but I'm posting here because maybe there's something I can do. 

Thanks for the attention

**Comment by ozne1** [comment]
I get this one at random sometimes too, happened even before I started using totsugeki, so it's not being caused by the tool indeed, someone might know what to do tho. As far as I've researched it might be either your router/internet settings not allowing this many connections happening, might be solved by meddling with it, do with caution tho, or your internet provider flagging your IP as doing suspicious shit and may be solved by changing public IP

**Comment by optix2000** [comment]
`context canceled` means it look longer than the 3 minutes totsugeki waits for the API request to finish. Given that `/statistics/set` is taking 30 seconds (which is quite long), I'm guessing either your Wifi reception or internet is bad and it's making stats uploads take a long time.

Try hard-wiring your connection and see if anyone else is using the internet at the same time since it might be slowing things down enough to cause the stats uploads to time out.

**Comment by JackKellar** [comment]
> `context canceled` means it look longer than the 3 minutes totsugeki waits for the API request to finish. Given that `/statistics/set` is taking 30 seconds (which is quite long), I'm guessing either your Wifi reception or internet is bad and it's making stats uploads take a long time.
> 
> Try hard-wiring your connection and see if anyone else is using the internet at the same time since it might be slowing things down enough to cause the stats uploads to time out.


200mb download and 100mb upload and its speed is consistent every time I need to upload something. I'm also wired, as I play on PC. I did speed tests before, during and after that and the speeds were constant.

**Comment by Lainadan** [comment]
I tried a couple of solutions that ended up working. I had the same problem, but a higher speed wired connection.

I closed my vpn softwares (hamachi and radmin), and also set my ip to automatically find a new one everytime, which I think it's the default setting. I had changed it to a static ip at one point and I guess that was also being a problem here.

There were times  before i had totsugeki that I had to wait for like 20 minutes... last time I opened, it took me only 1 minute.

**Comment by ozne1** [comment]
> I tried a couple of solutions that ended up working. I had the same problem, but a higher speed wired connection.
> 
> I closed my vpn softwares (hamachi and radmin), and also set my ip to automatically find a new one everytime, which I think it's the default setting. I had changed it to a static ip at one point and I guess that was also being a problem here.
> 
> There were times before i had totsugeki that I had to wait for like 20 minutes... last time I opened, it took me only 1 minute.

my problem persists, even with all those

**Comment by optix2000** [comment]
[I made a test build without timeouts](https://github.com/optix2000/totsugeki/releases/tag/v1.1.4-no-timeout).

Try using the test version and let me know if you still see the error message.

**Comment by Lainadan** [comment]
> > I tried a couple of solutions that ended up working. I had the same problem, but a higher speed wired connection.
> > I closed my vpn softwares (hamachi and radmin), and also set my ip to automatically find a new one everytime, which I think it's the default setting. I had changed it to a static ip at one point and I guess that was also being a problem here.
> > There were times before i had totsugeki that I had to wait for like 20 minutes... last time I opened, it took me only 1 minute.
> 
> my problem persists, even with all those

Have you tried runing totsugeki as admin? I had to do that aswell.

**Comment by JackKellar** [comment]
> [I made a test build without timeouts](https://github.com/optix2000/totsugeki/releases/tag/v1.1.4-no-timeout).
> 
> Try using the test version and let me know if you still see the error message.
> 
> If you're somehow still getting the error message, it means that GGST is the one cancelling the request because it's taking too long to load.
> 
> If you run GGST _without_ Totsugeki, do you see retry errors in GGST?

Oh yeah. Without Totsugeki it takes longer **and** still fails. Also when it does connect, disconnects midgame are very frequent. I'm gonna run the test version today and let you know by the end of the day.

**Comment by optix2000** [comment]
> > [I made a test build without timeouts](https://github.com/optix2000/totsugeki/releases/tag/v1.1.4-no-timeout).
> > Try using the test version and let me know if you still see the error message.
> > If you're somehow still getting the error message, it means that GGST is the one cancelling the request because it's taking too long to load.
> > If you run GGST _without_ Totsugeki, do you see retry errors in GGST?
> 
> Oh yeah. Without Totsugeki it takes longer **and** still fails. Also when it does connect, disconnects midgame are very frequent. I'm gonna run the test version today and let you know by the end of the day.

In that case there might not be anything Totsugeki can do to fix your problem. The logs are just there to help visualize and debug what GGST is doing. If your you're still getting failures _without_ Totsugeki then I'm suspecting this is an internet issue.

What do your [speedtests](https://www.speedtest.net) look like? What speeds do you get if you speedtest using a server in Tokyo, Japan? Does this happen at all times of the day or only certain times? Do you have anyone else using the internet?

**Comment by JackKellar** [comment]
> > > [I made a test build without timeouts](https://github.com/optix2000/totsugeki/releases/tag/v1.1.4-no-timeout).
> > > Try using the test version and let me know if you still see the error message.
> > > If you're somehow still getting the error message, it means that GGST is the one cancelling the request because it's taking too long to load.
> > > If you run GGST _without_ Totsugeki, do you see retry errors in GGST?
> > 
> > 
> > Oh yeah. Without Totsugeki it takes longer **and** still fails. Also when it does connect, disconnects midgame are very frequent. I'm gonna run the test version today and let you know by the end of the day.
> 
> In that case there might not be anything Totsugeki can do to fix your problem. The logs are just there to help visualize and debug what GGST is doing. If your you're still getting failures _without_ Totsugeki then I'm suspecting this is an internet issue.
> 
> What do your [speedtests](https://www.speedtest.net) look like? What speeds do you get if you speedtest using a server in Tokyo, Japan? Does this happen at all times of the day or only certain times? Do you have anyone else using the internet?

Before I say anything to that, I tried the test version yesterday exclusively and I didn't fail to connect a single time out of 7 launches (which is a first. I used to leave the game open just so I didn't have to deal with connection again). This is likely just be a good day/coincidence, but I'm glad I managed to play the game yesterday consistently.

My connection to Tokyo looks like this
![image](https://user-images.githubusercontent.com/88896098/129555388-be9209c0-1728-409c-b539-f1ff52e1d1c8.png)

**Comment by JackKellar** [comment]
> > > [I made a test build without timeouts](https://github.com/optix2000/totsugeki/releases/tag/v1.1.4-no-timeout).
> > > Try using the test version and let me know if you still see the error message.
> > > If you're somehow still getting the error message, it means that GGST is the one cancelling the request because it's taking too long to load.
> > > If you run GGST _without_ Totsugeki, do you see retry errors in GGST?
> > 
> > 
> > Oh yeah. Without Totsugeki it takes longer **and** still fails. Also when it does connect, disconnects midgame are very frequent. I'm gonna run the test version today and let you know by the end of the day.
> 
> In that case there might not be anything Totsugeki can do to fix your problem. The logs are just there to help visualize and debug what GGST is doing. If your you're still getting failures _without_ Totsugeki then I'm suspecting this is an internet issue.
> 
> What do your [speedtests](https://www.speedtest.net) look like? What speeds do you get if you speedtest using a server in Tokyo, Japan? Does this happen at all times of the day or only certain times? Do you have anyone else using the internet?

![image](https://user-images.githubusercontent.com/88896098/129589197-1e3ed3e8-4c03-48f4-9dd9-1ce51d652108.png)

new messages appeared in the console now

**Comment by optix2000** [comment]
I guess people's connections to Japan were worse than I expected when I had made the timeouts.

Unfortunately there's limited things Totsugeki can do to help in this situation. It seems like your connection to Tokyo is just not good enough to connect consistently.

The new messages you're seeing is the _server_ timing out. There is nothing Totsugeki can do here as this is enforced on ASW's side.

For now you can continue to use the test build. I'll remove the timeout on the next normal release of Totsugeki.

**Comment by JackKellar** [comment]
> I guess people's connections to Japan were worse than I expected when I had made the timeouts.
> 
> Unfortunately there's limited things Totsugeki can do to help in this situation. It seems like your connection to Tokyo is just not good enough to connect consistently.
> 
> The new messages you're seeing is the _server_ timing out. There is nothing Totsugeki can do here as this is enforced on ASW's side.
> 
> For now you can continue to use the test build. I'll remove the timeout on the next normal release of Totsugeki.

Thanks for helping us out with this. I hope they have a better solution to that soon.

I'm gonna close this as it seems to be solved.
