### ISSUE TITLE
Totsugeki unable to patch - Message: "Could not patch GGST..."

### ISSUE THREAD

**Issue by JerellDR** [optix2000/totsugeki#31]
**Does this issue happen when you don't use Totsugeki?**

No, the error is a result of totsugeki not being able to patch GGST

**Totsugeki Version and logs**
Version:  v1.1.4
![image](https://user-images.githubusercontent.com/2040514/129381631-99caa7fa-565b-4cb6-81dd-af51b110d1ab.png)

**Steps to Reproduce**

1. Start GGST from the steam library and run totsugeki.exe with the -no-launch argument or double click totsugeki.exe without the -no-launch argument
2. Wait for totsugeki.exe to run
3. Totsugeki errors out with the below message in step 3.1
 3.1 Could not patch GGST. Steam/GGST may be running as Administrator. Try re-running Totsugeki as Administrator
4. repeat steps 1-2. at step 1 run totsugeki.exe as administrator.  The message from step 3.1 will still show

The error occurs every time I try to run totsugeki.exe

**Comment by JerellDR** [comment]
Additionally, running the program from the command line gives the below error message.

![image](https://user-images.githubusercontent.com/2040514/129383505-6acda066-e14d-48d6-9942-319efa82bbe2.png)

**Comment by optix2000** [comment]
That's the first time I've seen that error. Is your game modded, or are you running an old version of Strive?
Try having [Steam Re-Verify the game](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB).

**Comment by JerellDR** [comment]
I don't have any mods running. I'll try to Re-Verify and see if that fixes the issue.

**Comment by JerellDR** [comment]
verifying the game solved the issue. Thanks for that suggestion. closing this out.
