### ISSUE TITLE
error in EnumProcessModules

### ISSUE THREAD

**Issue by ozne1** [optix2000/totsugeki#32]
tried to launch, and got this error as soon as the game itself opened
![image](https://user-images.githubusercontent.com/30633394/129427637-06a0f371-5483-4893-940a-4d40742830cc.png)
![image](https://user-images.githubusercontent.com/30633394/129427664-66abfc95-8680-4e17-866c-e1fca8902266.png)
roughly translates to: only a part of a request (...) or (...) was concluded.
it's also easily crashing with no error message as soon as the game opens

**Comment by optix2000** [comment]
Hm, v1.1.4 should have fixed this. I'll take another look at seeing if I can work around this.

For now, can you try launching GGST manually, and _then_ launch Totsugeki and see if it still happens?

**Comment by ozne1** [comment]
> Hm, v1.1.4 should have fixed this. I'll take another look at seeing if I can work around this.
> 
> For now, can you try launching GGST manually, and after GGST gets to the tile screen, launch Totsugeki and see if it still happens?

It's kinda random as when it happens, so can't say for sure if this solved, but tried opening 10 times in a row this way, and no problem happened.

**Comment by ozne1** [comment]
tested some more, after a while it decided to give me connection error before even the communicating with server thing, opening totsugeki with no launch gave me context canceled and the failed to upload code. 
![image](https://user-images.githubusercontent.com/30633394/129447977-3613c3ac-c289-46e6-b909-381cd1239b4f.png)
good connection speeds, good consistency, wired and I'm the only one connected.
I think the sheer amount of requests might be flagging my IP somewhere. meaning I can only open the game a few times a day

**Comment by optix2000** [comment]
>I think the sheer amount of requests might be flagging my IP somewhere. meaning I can only open the game a few times a day

GGST makes this number of requests normally. Totsugeki merely displays what GGST is doing for debugging purposes. If there's some sort of flagging going on, it would not be totsugeki's fault.

**Comment by optix2000** [comment]
> > Hm, v1.1.4 should have fixed this. I'll take another look at seeing if I can work around this.
> > For now, can you try launching GGST manually, and after GGST gets to the tile screen, launch Totsugeki and see if it still happens?
> 
> It's kinda random as when it happens, so can't say for sure if this solved, but tried opening 10 times in a row this way, and no problem happened.

`error in EnumProcessModules` should only happen when Totsugeki tries to patch GGST while GGST is still loading. The problem will be somewhat random since GGST may load a bit faster or slower depending on what else is running on your computer. By waiting for the game to fully load before launching Totsugeki, you work around the problem.

For now just work around the problem by launching Totsugeki manually after starting GGST. I'll draft up a test build with a fix for you tomorrow to test.

**Comment by optix2000** [comment]
Try the latest [beta build](https://github.com/optix2000/totsugeki/releases/tag/v1.2.1) and let me know if this still happens to you.

**Comment by ozne1** [comment]
haven't found it ever since, so I guess it's solved, but the connection errors seem to be a little more frequent when using it (as is it says I have no connection as soon as I open the game). might be my imagination, as I think it's a server/connection issue, not totsugeki itself

**Comment by optix2000** [comment]
Try the latest build and let me know if that fixes this error and reduces the number of connection errors.
https://github.com/optix2000/totsugeki/releases/latest

**Comment by optix2000** [comment]
Gonna assume the new build fixes this. Feel free to reopen if it's still happening even on the latest release.
