### ISSUE TITLE
really slow after match 

### ISSUE THREAD

**Issue by DontEatSmurfs** [optix2000/totsugeki#33]
im having issues with REALLY REALLY slow after matches, dont know if this is totsugeki issue or not but look at my server responses

![image](https://user-images.githubusercontent.com/88906479/129609285-cece0c56-4c8f-431f-b7dc-54cadbb07764.png)

**Comment by notKamui** [comment]
I suspect it's because you have average (or below average) upload speed. Since the server is in Japan, the upload speed needs to be really good to avoid those long times (and also, ASW better organizing their messy API ; like...a win should just be a win uploaded and then maybe the replay but in the background). I have the same problem. While I have amazing download speed and stability, my upload speed is the average french one (1-2Mb/s)

**Comment by DontEatSmurfs** [comment]
> I suspect it's because you have average (or below average) upload speed. Since the server is in Japan, the upload speed needs to be really good to avoid those long times (and also, ASW better organizing their messy API ; like...a win should just be a win uploaded and then maybe the replay but in the background). I have the same problem. While I have amazing download speed and stability, my upload speed is the average french one (1-2Mb/s)

i have a 20 mb/s up speed tho, here are my tests
![image](https://user-images.githubusercontent.com/88906479/129618626-1d03feb2-2085-4e39-9a21-1de143bb8899.png)

maybe its the ASW servers that are exploding ?

**Comment by notKamui** [comment]
i guess they're really that bad... they really need to optimize their /set API

**Comment by ozne1** [comment]
try checking your connection to tokyo, since the game has to connect to their servers over there after matches to update your profile

**Comment by optix2000** [comment]
> dont know if this is totsugeki issue or not but look at my server responses

Given only the `/stats/set` is slow, I would echo what @notKamui and @ozne1 are saying, in that it has to do with your upload speed to Tokyo.

> maybe its the ASW servers that are exploding ?

Also likely, or the internet between you and Japan is slow. Not all ISP's are built alike, and some have very poor connectivity to other countries (ie Australia to the rest of the world).

**Comment by optix2000** [comment]
Closing this out. Feel free to reopen if it's still happening.
