### ISSUE TITLE
Error warning at startup

### ISSUE THREAD

**Issue by MaximoAntolini22** [optix2000/totsugeki#34]
error warning at startup. Nothing happens but the game loads slightly slower than normal totsugeki.

**Does this issue happen when you don't use Totsugeki?** no

**Totsugeki Version and logs**

Version:  1.1.1

**Steps to Reproduce**

1. start up totsugeki
2.  its the first time it happens.
3. 
4.
![Captura de pantalla 2021-08-22 211208](https://user-images.githubusercontent.com/89364119/130374701-273467ef-afda-4238-bfca-8465875dc0a2.png)

**Comment by lynlevenick** [comment]
#32 suggests this is probably fixed by using a more up to date version of the program.

**Comment by HexaNoid1** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/50418567/130566913-85ad9c67-0bb2-44b9-955c-b6a0963f02d6.png)
Worth noting that this same error occurs in version 1.2.2

**Comment by MarcusChamberlain** [comment]
I got the same error, but only the first time I ran it. It seems once I ran totsugeki after opening GGST (as the comment above suggested), it ran fine every time after that (even when running totsugeki before opening GGST).

**Comment by guymanley** [comment]
Happened on the 3rd time I ran it. No arguments uses. I to have color and models mods installed. But those only affect in game assets.

---------------------------
Error
---------------------------
Totsugeki has encountered a fatal error.

Please report this to https://github.com/optix2000/totsugeki/issues

===================

Error: couldn't find base module for GGST-Win64-Shipping.exe

goroutine 7 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	runtime/debug/stack.go:24 +0xa5
main.panicBox(0x123fb00, 0xc00021c070)
	github.com/optix2000/totsugeki/main.go:60 +0x2d
main.main.func3.1()
	github.com/optix2000/totsugeki/main.go:236 +0x5c
panic(0x123fb00, 0xc00021c070)
	runtime/panic.go:965 +0x1c7
main.watchGGST(0x0, 0x1320038, 0xc000034d00)
	github.com/optix2000/totsugeki/main.go:130 +0x869
main.main.func3(0xc00000dff0, 0xc00000d0bb, 0x1320038, 0xc000034d00)
	github.com/optix2000/totsugeki/main.go:240 +0x8a
created by main.main
	github.com/optix2000/totsugeki/main.go:231 +0x994

---------------------------
OK   
---------------------------

**Comment by optix2000** [comment]
I added a fix in 71074eefcead9bd3806ce445d98cebe0a7fc5195 to hopefully fix this once and for all.

Check out the new release v1.4.0 once it comes out later today.
