### ISSUE TITLE
Get this error when starting

### ISSUE THREAD

**Issue by EpicCyanide** [optix2000/totsugeki#42]
![totsugeki_8onBUw9PI1](https://user-images.githubusercontent.com/86750075/131199495-983dec7b-a518-4344-89df-83be0f9643a9.png)

**Comment by optix2000** [comment]
Are you running the latest version of totsugeki?

**Comment by user1736** [comment]
Had the same issue when I was running an old version of totsugeki. Works fine with the latest version for me.

**Comment by optix2000** [comment]
Gonna close this out. This error shouldn't be possible on any of the recent versions of Totsugeki.
