### ISSUE TITLE
Not connection to network when running Totsugeki

### ISSUE THREAD

**Issue by Kalistence** [optix2000/totsugeki#44]
When launching the game with version 1.2.3 or 1.3 the game can't connect to the servers as if I wasn't connected to the internet at all. I tried out the launch options and when I use -no-proxy it connects, but is also as slow as usual.
**Does this issue happen when you don't use Totsugeki?**

Only happens when launching through Totsugeki.
**Totsugeki Version and logs**

Version: 1.2.3 and 1.3
![image](https://user-images.githubusercontent.com/89701921/131225178-cceea8e5-c6c5-4043-88e2-06a325d7dd3b.png)

**Comment by optix2000** [comment]
Can you screenshot the output of the Totsugeki window when this happens? Do you have GG-Struggle installed?

**Comment by Kalistence** [comment]
No I don't have GG-Struggle installed.

![image](https://user-images.githubusercontent.com/89701921/131233536-f9763d49-a825-426c-b6b7-e8f4461e11bc.png)

**Comment by optix2000** [comment]
Weird, do you have some firewall blocking Totsugeki? Looks like it's not getting any traffic at all from GGST.

**Comment by Kalistence** [comment]
Sorry for the very late reply, was really busy the last week. As far as I know nothing should block Totsugeki, I even allowed it in the Kaspersky Firewall manually.

**Comment by optix2000** [comment]
If you go to http://127.0.0.1:21611 in your browser while Totsugeki is running, does it load?

**Comment by janneslessmann** [comment]
@Kalistence So any updates here? I was having this issue too, around the same time you had it. But it solved itself on further updates of Totsugeki. Do you still encounter the error in the newest version?

**Comment by optix2000** [comment]
Closing as it looks like this isn't happening to anyone anymore.
