### ISSUE TITLE
Totsugeki not opening

### ISSUE THREAD

**Issue by alexprimeiro** [optix2000/totsugeki#45]
I have downloaded totsugeki.exe but when I try to run the executable nothing happens. I've tried disabling firewall and there is no anti-virus that could make this clash.

**Comment by optix2000** [comment]
Which version of Totsugeki? What do you mean "nothing happens"? Does Totsugeki launch at all?

**Comment by alexprimeiro** [comment]
> Which version of Totsugeki? What do you mean "nothing happens"? Does Totsugeki launch at all?

No instance of a Totsugeki process opens, I'm running the 1.3.0 version released after the Jack-o release

**Comment by optix2000** [comment]
What happens if you try to launch Totsugeki through the command prompt? (https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/)
You can drag and drop Totsugeki into the command prompt (and then hit enter) to run it.

**Comment by optix2000** [comment]
Glad it works for you, but kinda weird Totsugeki won't start normally. Not sure what's going on here.

**Comment by optix2000** [comment]
Gonna close this out for now. Feel free to reopen if this is happening again.
