### ISSUE TITLE
New set of unsafe speedups causes Quick Match to Disconnect

### ISSUE THREAD

**Issue by fefo-dev** [optix2000/totsugeki#50]
Totsugeki 1.4.1, coming from 1.3.0 (no issues there)

Testing:

First run, after getting to the main menu and entering Quick Match, had a long wait time with several async logs from Totsugeki until a disconnect ("Network features unavailable" blabla) happened. Hitting normal online prompted a reconnection and from there I could enter the tower/park and play.

Back to the menu I tried to enter Quick Match again. Same behavior, but without any notification on Totsugeki.

Normal mode works as expected of course.

---

Unless there was any change outside of the listed ones it should be either an issue with https://github.com/optix2000/totsugeki/pull/47 or a regression from https://github.com/optix2000/totsugeki/pull/46. I could do tests in each later but should be easy enough to track.

Thanks for supporting it still btw, it certanly saved the game for me and a bunch of people.

**Comment by optix2000** [comment]
Thanks for testing the unsafe speedups in 1.09. I don't use quick match so this was an oversight. Will have to see if I can repro this weekend.

**Comment by optix2000** [comment]
Confirmed. GGST hangs and then disconnects if you use Quick Match with Totsugeki Unga Bunga.
Totsugeki also locks up on shutdown.

**Comment by fefo-dev** [comment]
Just checked, Ranking and Replay also disconnects. Obvously can't get do anything inside those modes so it's more to check. Viewing R-Code from lobby players worked fine, dunno if theres other online features.

Totsugeki closed normally here in every occasion. If anything I'm using the normal version it with -no-launch -no-close -unga-bunga parameters.

**Comment by optix2000** [comment]
Confirmed to be #47.

@Borengar: I don't know if you want to take a shot at trying to fix this. Otherwise I'll take a stab this weekend.

**Comment by Borengar** [comment]
GGST is performing a new login every time one of those online features is used (wtf why). This makes the stats_get_prediction start again, which then gets stuck at some point.

**Comment by fefo-dev** [comment]
Looks like https://github.com/optix2000/totsugeki/pull/51 fixed all errors. No issues on Quick Match, Ranking or Replay.
