### ISSUE TITLE
Fatal error when opening totsugeki

### ISSUE THREAD

**Issue by MagnusNordboe** [optix2000/totsugeki#53]
I'm launching Totsugeki as admin from the Downloads folder on a 64bit win10 machine. Every time, it launches Strive then immediately gives me a "fatal error" message. 

[Here's the message in question](https://i.imgur.com/eCtLM3U.png)

Strive still launches. After clicking OK Totsugeki closes.

I'm also running Steam as admin which I why I do so for totsugeki.

**Comment by optix2000** [comment]
What version of Totsugeki are you running?

That stack trace is referring to really old code. Can you try the latest version and see if this still happens? This error should be fixed already.

**Comment by MagnusNordboe** [comment]
Ah you're right, I'm running 1.3.0.

Didn't realize I was running an old version, apologies.

**Comment by optix2000** [comment]
The latest version auto updates so you won't need to check anymore.
