### ISSUE TITLE
(Unga) Relauching GGST without closing Totsugeki greatly increases startup time

### ISSUE THREAD

**Issue by fefo-dev** [optix2000/totsugeki#55]
https://files.catbox.moe/mzj0wx.mp4

Test method: launched and closed GGST sequentialy. Went as far as the floor menu but no change there, all took ~6-8s. Relaunching Totsugeki -unga fix the issue.

Even accounting the time it took for the first startup to "warm up" the difference is huge. 4th one happened to be the slowest of all but given the consistency it should be just communication differences.

Two separate tests with normal Totsugeki gave me ~1:10 to menu, so the speedups are either not in effect or being greatly limited by something.

---

As this isn't the intended usage I'm sharing it for debug purposes (reason why I use the -no-close flag), but in case there's no fix you could add a note next to -no-close.

**Comment by Borengar** [comment]
Side effect of the fix in #51. Because the stats_get_prediction stays in finished state forever now every game start after the first one will be slower.
Gonna try to get a fix out soon ™️

**Comment by optix2000** [comment]
Thanks for the report and fix!

**Comment by fefo-dev** [comment]
Had a short test session and the PR worked, closing and opening the game again didn't reproduced the issue.

After a few games I had a network error - training in lobby, quit to floor menu and tried to reenter > disconnect - likely unrelated to 🐬 but here are the steps for further testing.
This network error threw me back to start menu (normal behaviour sadly). Entered the main menu (still disconnected, normal) and then went to Network to trigger a reconnect. This reconnect however was a slow one, with Totsugeki window behaving just like the reported cases.
Does it pass through different steps from start? I clearly remember reconnecting from there with speedups in effect.

**Comment by optix2000** [comment]
So I just did some tests with R-Codes with #57. This works with viewing R-Codes in the park or tower, but doesn't work if you view multiple R-Codes through Rankings since there's no `/tus/read` call to reset it.

I'm thinking it might be better to just do some heuristics.

- If all expected calls are complete, reset.
- If a call that was complete gets called again, reset and clear all the queues.

This should in theory cover everything.

**Comment by Borengar** [comment]
Damn it 😆 I only tried tower and replays and loading multiple r-codes worked there.
I'm gonna take another look at it and see if I can solve it your way. Using those conditions to reset sounds a lot better than using random requests that come after the stats ones.

**Comment by optix2000** [comment]
🙏 https://github.com/optix2000/totsugeki/releases/tag/v1.5.0
