### ISSUE TITLE
Error when starting the Unga Bunga edition

### ISSUE THREAD

**Issue by DavrK** [optix2000/totsugeki#63]
![image](https://user-images.githubusercontent.com/25210424/134782708-37e0cd65-224b-4c17-943e-bd7cb26ed726.png)

**Comment by DavrK** [comment]
(the regular version works fine)

**Comment by Borengar** [comment]
Does the console output contain any errors?  
This seems to be caused by the `-unsafe-cache-env` part of unga-bunga.

**Comment by DavrK** [comment]
![image](https://user-images.githubusercontent.com/25210424/134785612-a6d689a7-72ef-4f60-90c5-651f5221cece.png)

**Comment by Borengar** [comment]
I get this exact error when I block the exe in the firewall. Can you make sure that the totsugeki-unga-bunga.exe is not blocked by your firewall or anti virus?

You can also try to start the normal totsugeki.exe with -unga-bunga parameter by using a shortcut like this:
![image](https://user-images.githubusercontent.com/5701614/134786349-85a9a2bd-6529-48bc-91a0-26744f5787a8.png)
If that works then it's most likely a security feature blocking the totsugeki-unga-bunga.exe somewhere.

**Comment by DavrK** [comment]
Yup, that fixed it. What had happened was that when I tried to use the tool the other day, it tried to auto update itself and my antivirus (Bitdefender) blocked it and quarantined the file. I then re-downloaded the tool thinking it would've solved the issue, which it partially did except for the fact that it also got blocked by the firewall the first time without my knowledge, but its all fixed now. Ty
