### ISSUE TITLE
Error message when close the game.

### ISSUE THREAD

**Issue by Raziel-LaFey** [optix2000/totsugeki#65]
![Sem título](https://user-images.githubusercontent.com/91440123/134829028-0757ca52-83f4-4c20-b361-10e5cd8497f5.png)

**Comment by optix2000** [comment]
Confirmed.

**Comment by owengalenjones** [comment]
Seconded:

![Error 12_16_2021 11_07_54 PM](https://user-images.githubusercontent.com/690817/146503880-29808ece-89a0-4379-ae14-1e9dba91ed5d.png)

**Comment by janneslessmann** [comment]
> Seconded:
> 
> ![Error 12_16_2021 11_07_54 PM](https://user-images.githubusercontent.com/690817/146503880-29808ece-89a0-4379-ae14-1e9dba91ed5d.png)

Did you behave different in any way when you were using Totsugeki before this error occurred?
