### ISSUE TITLE
Totsugeki stopped connecting to the internet

### ISSUE THREAD

**Issue by joaquincarreno** [optix2000/totsugeki#66]
Since a few days ago, when I try to use totsugeki with the game I recieve a `Failed to update totsugeki: could not get latest release version number.`. Then, when the game opens and I press a button to get past the Title Screen the game shows an error message saying there is no connection is if I was oppening the game in Steam's offline mode. Right when this happens I get the next message:
![image](https://user-images.githubusercontent.com/64704150/135012437-88ac385c-b55d-428d-a262-d61783c065bc.png)
Translation: 
`Post "https://ggst-game.guiltygear.com/api/sys/get_env" : deal tcp 3.114.111.171:443: connectex: There was an attempt to access a socket that`s not allowed by it's 
privileges`
Note that I've tried oppening totsugeki as an Administrator.

**Does this issue happen when you don't use Totsugeki?**
No, it works normally when I don't use it.

**Totsugeki Version and logs**
It started when I updated to v1.7.0 but I've tried with v1.3 and 1.6, both versions that used to work

**Steps to Reproduce**
No special steps, happens everytime.

**Comment by Borengar** [comment]
Looks similar to #63. Totsugeki can't reach GitHub and Guilty Gear servers.
The exe might be blocked by your antivirus or firewall.

**Comment by joaquincarreno** [comment]
It was bit defender forgeting the exception with the update.
