### ISSUE TITLE
V1.10 Update

### ISSUE THREAD

**Issue by Borengar** [optix2000/totsugeki#68]
New GGST update 1.10 released today.
Using Totsugeki in normal mode without any unsafe features should still work and give a noticeable speedup (about 1:30 -> 0:30 for me, EU).

I only looked at the loading screen so far, but it looks like ASW massively reduced the amount of statistics/get requests that are done.
Connection is still not keep-alive, which is why Totsugeki still gives a good speed boost.
Did some initial tests with reduced requests in ungabunga mode and I get around 10 seconds for the loading screen.

**Comment by Borengar** [comment]
R-Code has not been changed at all. It's still the exact same list of requests. No change needed there.

**Comment by optix2000** [comment]
https://github.com/optix2000/totsugeki/releases/tag/v1.8.0
