### ISSUE TITLE
Parameter is incorrect?

### ISSUE THREAD

**Issue by St1nGxD** [optix2000/totsugeki#71]
**Does this issue happen when you don't use Totsugeki?**

**Totsugeki Version and logs**

Version: 

**Steps to Reproduce**

1. 
![Screenshot 2021-12-06 042655](https://user-images.githubusercontent.com/95598517/144777391-1d333bcd-52d4-456b-a4bd-a3b58c50b29f.png)

2. for some reason the it does this when i start totsugeki.exe, plz fix i don't intend to communicate with these servers...

**Comment by notKamui** [comment]
you're using an old version.

try with the latest one.

**Comment by optix2000** [comment]
Should be fixed with the latest release of v1.9.0.
