### ISSUE TITLE
Error with PID 19132 at offset 0x0: couldn't find base module for GGST-Win64-Shipping.exe

### ISSUE THREAD

**Issue by valenjojo** [optix2000/totsugeki#75]
When i try to start totsugeki the error "Error with PID 19132 at offset 0x0: couldn't find base module for GGST-Win64-Shipping.exe" happens, i tried starting totsugeki after GGST and it didn't work. Making an exception in my antivirus/shield or starting as an administrator didn't work.

![totsugeki error](https://user-images.githubusercontent.com/75908043/149687047-4ec06ea6-e45d-4530-92bb-d43e53e19bfb.png)

 I'm using the latest version as you can see in the image

**Comment by optix2000** [comment]
Should be fixed with the latest release of v1.9.0.
