### ISSUE TITLE
Modifying statistics data

### ISSUE THREAD

**Issue by halvnykterist** [optix2000/totsugeki#77]
Hi,
I've been working on https://github.com/halvnykterist/rating-update/ and was wondering how feasible it would be to modify stat request calls to replace a player's character level with their rating from the website. I've poked around a bit but due to my poor familiarity with the language I'm not entirely sure what the best approach would be for this.
I'd be grateful for any hints on where to start!

**Comment by optix2000** [comment]
Totsugeki (currently) doesn't do any protocol decoding and just passes raw data between GGST and ASW. This means that you'll need to serialize/deserialize the API yourself, or make your edits raw.

There's [a bit of code](https://github.com/optix2000/totsugeki/blob/master/proxy/proxy.go#L67-L68) I left in specifically for the purpose of being able to play around with the API payloads. I'd start by adding some code to dump or print the API payloads and then look at how you'd want to parse and modify it.

You can do something like this to quickly print out the API.
```go
reader := io.TeeReader(resp.Body, w) // For dumping API payloads
buf, err := io.ReadAll(reader)
fmt.Println(string(buf))
```

For character level, if I remember correctly, is raw JSON as part of one of the `/stats/get` calls, so it's easier than some of the other data.

**Comment by optix2000** [comment]
Totsugeki uses [chi](https://github.com/go-chi/chi) to implement the proxy part. You can look at the chi docs to see how the [handler functions](https://github.com/optix2000/totsugeki/blob/master/proxy/proxy.go#L205) work (like `HandleCatchall()`), and make your own handler to modify the stat calls.

**Comment by halvnykterist** [comment]
Thanks for the tips, I'll start investigating here then!

**Comment by halvnykterist** [comment]
Since showing rating in totsugeki's been implemented now I can probably close this 🙂
