### ISSUE TITLE
Background activity causing hitching during gameplay.

### ISSUE THREAD

**Issue by pyide** [optix2000/totsugeki#79]
When totsugeki.exe is active (reg or unga-bunga), I notice the game stuttering frequently, both online and even in training mode standby, but online during an active match it's worse, or at least more noticeable.

During these stutters, ping indicator and rollback frames aren't spiking, but when playing with friends they also are impacted by these, and can tell a real difference when I'm using it vs when I'm not.  it's like the program is stealing priority and causing GGST to freeze temporarily. I've tried maxing the priority of GGST processes and decreasing totsugeki's to the lowest which does seem to help a little, but doesn't seem to fully get rid of this behavior entirely.  Perhaps adjusting the affinity to use a less in demand core may have some impact if it priority based. 

**Does this issue happen when you don't use Totsugeki?**
No, it does not happen when I'm not using totsugeki. I haven't been using totsugeki.exe for months now because of this issue, I'm only trying it again since there are new versions out there and I was curious. I tried tweaking so many things to alleviate this specific issue but the only thing that got rid of these hitches is simply not using totsugeki. System is 4790k/nv2060/16GB/Win10

**Totsugeki Version and logs**
All versions I've tried, except maybe some of the early ones. I don't remember which at this point, been so long. I don't know where to find or how to generate a log. 

**Steps to Reproduce**

Play the game w/ totsugeki active.

This could very well just be the fault of my own setup somewhere since I haven't much discussion of this behavior from others, but it's impossible to troubleshoot, the only thing I've found is that gameplay is perfectly smooth without it active, and stutters a lot with it active. I am curious to know if there is any possible way to set totsugeki to only speed up the initial server connection and do absolutely nothing else, and then see what happens. Is that even possible? All that really matters to me is reducing the initial wait, anyway. Thanks!

**Resolved**

Switching the CPU affinity of tosugeki.exe to just use the last thread, and dropping the priority all the way seemed + increasing priority of GGST seemed to mitigate the issue for now. Project Lasso is set so I don't have to keep doing these tweaks manually. Not sure why it's interrupting things normally, but I'm satisfied with the simple workaround.

**Comment by janneslessmann** [comment]
It doesn't happen to me and I use Totsugeki pretty much daily. Can you provide additional information? (logs, specs...)
