### ISSUE TITLE
Does this program causes desync?

### ISSUE THREAD

**Issue by reffychan** [optix2000/totsugeki#8]
Alright so I just tried out using this fix and sure enough I get in after 30 seconds, The issue, though, is the first 2 matches I played they resulted in significant desync that resulted in 2 loses that I never realized. Looking at the replays I saw 1 match that ended earlier than I recall, and the other replay it just becomes a bunch of toddlers playing. I don't know if it was because of this program or just dumb luck though I have never experienced desync before now so I don't know.

**Comment by optix2000** [comment]
Not possible for Totsugeki to be involved here. It deals _only_ with GGST server communications; like stats, matchmaking, lobby, etc. It doesn't touch any of peer-to-peer communications that GGST uses for actual matches.

Imagine if all the match communications had to use ASW servers. You'd have lag as bad as the loading screen.
