### ISSUE TITLE
Not an issue but... You don't need Totsugeki anymore after new patch.

### ISSUE THREAD

**Issue by HelgenX** [optix2000/totsugeki#82]
The game loads about as fast as Totsugeki does after the latest patch, but I want to thank the developer of this for their fine work, as it helped me the entire time before this new patch!

**Comment by optix2000** [comment]
Confirmed.

GGST now properly does keepalive and Totsugeki isn't necessary anymore. Unga-bunga still speeds things up if people still want to use that.

Thanks for checking!
