### ISSUE TITLE
Release the rating-update RC as a full release

### ISSUE THREAD

**Issue by halvnykterist** [optix2000/totsugeki#83]
It's probably had enough testing by now.

Could probably do to put instructions related to it in the readme too, since that and ungabunga are the only reasons to really use totsugeki now.

**Comment by dAN0n** [comment]
It needs to be updated with Bridget support though.

**Comment by optix2000** [comment]
https://github.com/optix2000/totsugeki/releases/tag/v1.10.0

New build here. Will move to stable soon.

**Comment by optix2000** [comment]
https://github.com/optix2000/totsugeki/releases/tag/v1.10.1

Stable build released.
