### ISSUE TITLE
Request: option to close totsugeki.exe when Strive closes

### ISSUE THREAD

**Issue by onaront** [optix2000/totsugeki#9]
Right now the program continues to wait for the Strive process even when Strive closes. It would be nice to have an option to close after Strive does (I imagine that most people will close totsugeki.exe after exiting Strive anyways)

**Comment by optix2000** [comment]
If people are using totsugeki as a launcher for GGST (and most people probably are), then I think this makes sense to have.

The only question is whether or not it makes sense to make auto-close the default option.

I'll leave this open for a bit to gather people's thoughts. At least for now I'm leaning toward auto-close as the default.

**Comment by FogKnight22** [comment]
Personally, this would be a great option to have (and for me, I would prefer it as the default option but still alterable for those who would prefer to have the option to disable it if they want to). I use Totsugeki at the moment as the launcher of the game, so I would close it as well when I am done playing. Having it close as GGST's process ends would be a really great QoL feature.

**Comment by notKamui** [comment]
i would also tend towards making the auto-close the default option. This would also stay in the same vein as the other options (--no-close).

**Comment by fefo-dev** [comment]
Outside of debugging the only case where I see leaving it open being somewhat useful is if you need to close and reopen the game due to servers acting up - which is normally avoided as even with totsugeki loadtimes are subpar at best.

Close by default with a toogle seems reasonable.

**Comment by optix2000** [comment]
"Nightly" build available here: https://github.com/optix2000/totsugeki/actions/runs/1080104734

Otherwise just wait for the next release.
